version: 2
jobs:
  code-style:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm run bootstrap
      - run:
          name: Check code style
          command: npm run style

  test:
    docker:
      - image: circleci/node:latest
        environment:
          DB_ENVIRONMENT: test
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Install dependencies
          command: |
            npm run bootstrap
            sudo apt-get install postgresql-client
      - run:
          name: Create test database
          command: |
            psql -U postgres -h localhost -p 5432 -c "CREATE DATABASE \"qhacks-test-database\";"
      - run:
          name: Run tests and send coverage data
          command: npm run test-with-coverage

workflows:
  version: 2
  run-tests:
    jobs:
      - code-style
      - test
